/*
  Copy your Supabase PROJECT URL and ANON/PUBLISHABLE KEY here.
  Never put a Supabase service-role key here.
*/
window.POLYCLASH_CONFIG = {
  SUPABASE_URL: "PASTE_YOUR_SUPABASE_PROJECT_URL_HERE",
  SUPABASE_ANON_KEY: "PASTE_YOUR_SUPABASE_ANON_OR_PUBLISHABLE_KEY_HERE"
};
